version: "2"

linters:
  default: standard
  enable:
    - gocritic
    - cyclop
    - gocognit
    - errorlint
    - gosec
    - durationcheck
    - makezero
    - nilerr
    - nilnil
    - misspell
    - modernize
  exclusions:
    generated: lax

formatters:
  enable:
    - gofmt
    - goimports
    